/** \file logging.c
 * Logger Rollster
 *
 * Asynchronous Logging Library for LibreSplit based on threads, circular queues,
 * hopes and dreams.
 *
 * This library is not built to support more than one instance of LibreSplit running
 * at a time. That would require the instances to be able to either have each its own
 * logfile (maybe `libresplit_date_pid`) or inter-process communication.
 */
#include "logging.h"
#include "settings/utils.h"
#include "src/timer.h"
#include "src/utils.h"

#include <dirent.h>
#include <linux/limits.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <time.h>

/*! The log queue, used as buffer */
static LogQueue logQueue;
/*! Atomic bool used to keep the thread active, might be used for clean closing in future */
static atomic_bool logging_active;
/*! Holds the filename for the logfile */
static char log_filename[NAME_MAX];

/**
 * Takes a filename and tries to extract the date from its name.
 *
 * Assumes that the names are correct and generated by LibreSplit, other stuff
 * is ignored.
 *
 * @param filename The name of the file to parse
 * @return -1 if there is an error. The timestamp integer otherwise.
 */
static int filename_to_datestamp(const char* filename)
{
    // "LibreSplit" is 10 chars long
    // If the name doesn't start with "libresplit" and the 11th char is not "_"
    // don't try to convert
    if (strncmp(filename, "libresplit", 10) != 0 || filename[10] != '_') {
        return -1;
    }

    // Pointer magic, point to 10 chars after the begin of string to skip "libresplit"
    // then another one for the underscore
    const char* date = filename + 10 + 1;

    struct tm parsed = { 0 };

    char* end = strptime(date, "%Y-%m-%d", &parsed);

    if (end == NULL || end - date != 10 || strcmp(end, ".log") != 0) {
        // Filename doesn't finish with ".log"
        return -1;
    }

    return (parsed.tm_year + 1900) * 10000 + (parsed.tm_mon + 1) * 100 + parsed.tm_mday;
}

/**
 * Deletes logs older than the configured amount of days.
 *
 * Uses trickery and tomfoolery to convert a YYYY-MM-DD timestamp into an integer
 * that can be compared.
 */
static int rotate_logs(void)
{
    if (cfg.logging.rotate_after_days.value.i == 0) {
        LOG_INFO("Cutoff Days set to zero, skipping rotation");
        return 0;
    }
    DIR* dir;
    struct dirent* entry;
    time_t now = time(NULL);
    struct tm cutoff_time;

    if (now == (time_t)-1 || localtime_r(&now, &cutoff_time) == NULL) {
        LOG_ERR("Cannot get time or convert it to local time");
        return -1;
    }

    cutoff_time.tm_hour = 0;
    cutoff_time.tm_min = 0;
    cutoff_time.tm_sec = 0;
    cutoff_time.tm_mday -= cfg.logging.rotate_after_days.value.i;

    if (mktime(&cutoff_time) == (time_t)-1) {
        LOG_ERR("Cannot calculate log rotation cutoff date");
        return -1;
    }

    // Convert the date into an easily comparable integer
    int cutoff_date = (cutoff_time.tm_year + 1900) * 10000 + (cutoff_time.tm_mon + 1) * 100 + cutoff_time.tm_mday;

    char data_path[PATH_MAX];
    get_libresplit_data_folder_path(data_path);
    strcat(data_path, "/logs");

    dir = opendir(data_path);
    if (!dir) {
        LOG_ERR("Cannot open log directory for rotation");
        return -1;
    }

    while ((entry = readdir(dir)) != NULL) {
        // XXX: [Penaz] [2026-10-01] Big Assumption: The log names are valid
        int file_date = filename_to_datestamp(entry->d_name);
        if (file_date < 0) {
            // Date parsing error
            LOG_WARNF("File %s not rotated: cannot parse date.", entry->d_name);
            continue;
        }
        if (file_date >= cutoff_date) {
            // File too recent, don't rotate
            LOG_DEBUGF("Logfile %s not rotated: too recent", entry->d_name);
            continue;
        }

        char path[PATH_MAX];
        size_t written = snprintf(path, sizeof(path), "%s/%s", data_path, entry->d_name);

        if (written < 0 || written >= sizeof(path)) {
            LOG_ERRF("Path too long: %s", entry->d_name);
            continue;
        }

        struct stat st;

        if (lstat(path, &st) != 0) {
            LOG_DEBUGF("Cannot stat %s, skipping", path);
            continue;
        }

        if (!S_ISREG(st.st_mode)) {
            LOG_DEBUGF("Skipping %s: not a regular file", path);
            continue;
        }

        if (unlink(path) == 0) {
            LOG_INFOF("Rotated LogFile %s: found to be older than %d days.", path, cfg.logging.rotate_after_days.value.i);
        } else {
            LOG_WARNF("Cannot rotate LogFile %s", path);
        }
    }

    closedir(dir);
    return 0;
}

/**
 * Initializes the log queue, ready to receive messages
 */
void initLogQueue(void)
{
    logQueue.head = 0;
    logQueue.tail = 0;
    char date[16];
    set_date(date);
    int written = snprintf(log_filename, NAME_MAX, "libresplit_%s.log", date);
    if (written <= 0 || written >= PATH_MAX) {
        perror("Path to logfile too long. Disabling logger.");
        logging_active = 0;
        return;
    }
    pthread_mutex_init(&logQueue.lock, NULL);
    pthread_cond_init(&logQueue.cond, NULL);
    logging_active = 1;
    if (rotate_logs() != 0) {
        LOG_ERR("Cannot rotate logs");
    }
}

/**
 * Underlying function to all the LOG_* macros
 *
 * Works as a producer.
 *
 * @param[in] fmt The message to print in the log or the format string
 */
void logMessage(const char* fmt, ...)
{
    // Lock the mutex for writing
    pthread_mutex_lock(&logQueue.lock);
    // If the queue is full, wait (bottleneck)
    while ((logQueue.tail + 1) % LOG_QUEUE_SIZE == logQueue.head) {
        // NOTE: [Penaz] [2026-09-30] It might be more sane to drop new logs
        // ^ instead of blocking any other possible calling thread. (Early return)
        pthread_cond_wait(&logQueue.cond, &logQueue.lock);
    }
    // Create a timestamp for the log
    char timestamp[64];
    time_t current_time = time(NULL);
    struct tm* t = localtime(&current_time);
    strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S", t);
    // There is space in the queue, add a new message
    va_list args;
    va_start(args, fmt);
    // Put the timestamp first...
    snprintf(logQueue.message_queue[logQueue.tail], LOG_STR_LEN, "%s | ", timestamp);
    // The remaining space is for the message
    vsnprintf(logQueue.message_queue[logQueue.tail] + strlen(timestamp) + 3, LOG_STR_LEN - strlen(timestamp) - 1, fmt, args);
    va_end(args);
    logQueue.tail = (logQueue.tail + 1) % LOG_QUEUE_SIZE;

    // Signal a possibly waiting logging thread
    pthread_cond_signal(&logQueue.cond);
    // Unlock the mutex
    pthread_mutex_unlock(&logQueue.lock);
}

/**
 * Pops a message from the log queue, writing it into console
 * and the log file. Just a utility.
 *
 * @param logfile The File pointer to write into
 */
static void pop_message(FILE* logfile)
{
    // Remove a message from the queue
    // We don't empty the whole queue to avoid being a bottleneck for the
    // addition of new messages.
    // Log to console
    if (cfg.logging.print_to_console.value.b) {
        printf("%s", logQueue.message_queue[logQueue.head]);
    }
    // Log to file
    fprintf(logfile, "%s", logQueue.message_queue[logQueue.head]);
    // Flush the file immediately to disk, in case something crashes
    fflush(logfile);
    logQueue.head = (logQueue.head + 1) % LOG_QUEUE_SIZE;
}

/**
 * The logging thread, writes the queued messages in the log.
 *
 * Works as a consumer
 *
 * @param arg Unused.
 */
void* loggingThread(void* arg)
{
    prctl(PR_SET_NAME, "LS Logger", 0, 0, 0);
    char data_path[PATH_MAX];
    get_libresplit_data_folder_path(data_path);
    strcat(data_path, "/logs/");
    strcat(data_path, log_filename);
    FILE* logfile = fopen(data_path, "a");
    if (!logfile) {
        perror("Failed to open log file");
        return NULL;
    }
    while (atomic_load(&logging_active)) {
        // Lock the mutex for reading
        pthread_mutex_lock(&logQueue.lock);
        // If the queue is empty, wait
        while (logQueue.head == logQueue.tail) {
            pthread_cond_wait(&logQueue.cond, &logQueue.lock);
            // We got signalled by the main thread to close up
            if (!atomic_load(&logging_active)) {
                break;
            }
        }
        pop_message(logfile);
        // Unlock the mutex
        pthread_mutex_unlock(&logQueue.lock);
    }
    // We're closing the logger, empty the remaining logs...
    while (logQueue.head != logQueue.tail) {
        pop_message(logfile);
    }
    // ... and close the logfile
    fclose(logfile);
    return 0;
}

/**
 * Function to close the logger thread.
 *
 * This is needed because while we're closing, we might be waiting for
 * the queue to fill up. If that's the case, we signal the thread to continue
 * after setting logging_active to false.
 */
void close_logger(void)
{
    atomic_store(&logging_active, 0);
    LOG_DEBUG("Shutting down logger thread...")
    // Signal the logging thread to continue, so to hit the closing condition,
    // in case it is waiting for the log queue to fill. If it isn't, the signal
    // should be ignored.
    pthread_cond_signal(&logQueue.cond);
}
